#!/usr/bin/env bash
# Loop iterations with if else and printing things

i="0"
while [ $i -lt 10 ]
do
if [ $i -eq 3 ]
then
	echo "bad luck"
	i=$((i+1))
elif [ $i -eq 7 ]
then
	echo "good luck"
	i=$((i+1))
else
	echo "Best School"
	i=$((i+1))
fi
done
