#!/usr/bin/env bash
# Using case to interrupt a while loop

i="1"
while [ $i -lt 21 ]
do
echo $i
i=$((i+1))
case $i in
	4)
		echo $i
		echo "bad luck from China"
		i=$((i+1))
		;;
	9)
		echo $i
		echo "bad luck from Japan"
		i=$((i+1))
		;;
	17)
		echo $i
		echo "bad luck from Italy"
		i=$((i+1))
		;;
esac
done
